### ISSUE TITLE
Firefox Extension Permission

### ISSUE THREAD

**Issue by DomDomHaas** [Decentr-net/charon#206]
Hi there

Can you explain wit the Dec Extension needs access to all data on a website?

Or more specific why it would need "Access your data for all web sites" which potential gives access to usernames and passwords?
https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-your-data-for-all-websites

**Comment by nanikeev** [comment]
Permission "access all websites" is used only in context of collecting cookies so that WebRequest can have an ability to listen login requests on pages.
This is needed so that we can separate regular and login cookies (if we get login cookie with the same email that user registered with we award double the PDV) 
All of our code is open source and you can always see that Charon does NOT save any usernames and/or passwords. Thank you!
